# Git (Version Control)

*Author: Charles J. Geyer*


## License

This work is licensed under a Creative Commons
Attribution-ShareAlike 4.0 International License
(<http://creativecommons.org/licenses/by-sa/4.0/>).


## R

 * The version of R used to make this document is `r getRversion()`.

 * The version of the `rmarkdown` package used to make this document is `r packageVersion("rmarkdown")`.

 * The version of the `knitr` package used to make this document is `r packageVersion("knitr")`.

## Version Control

### What is It?

 * revision control

 * version control

 * version control system (VCS)

 * source code control

 * source code management (SCM)

 * content tracking

all mean the same thing.

It isn't just for source code.  It's for any "content."

I use it for

 * classes (slides, handouts, homework assignments, tests, solutions),

 * papers (versions of the paper, tech reports, data, R scripts for data
    analysis),

 * R packages (the traditional source code control, although there is a lot
    besides source code in an R package),

 * notes (long before they turn into papers, I put them under version
    control).

### Very Old Fashioned Version Control

```
asterLA.7-3-09.tex    asterLA.10-3.tex
asterLA.7-16.tex      asterLA.10-3c.tex
asterLA.7-16c.tex     asterLA10-4.tex
asterLA.7-19.tex      asterLA10-4c.tex
asterLA.7-19c.tex     asterLA10-4d.tex
asterLA.7-19z.tex     asterLA01-12.tex
asterLA8-19.tex       asterLA01-12c.tex
asterLA8-19c.tex      asterLA01-20.tex
asterLA.9-1.tex       asterLA01-20c.tex
asterLA.9-1c.tex      asterLA02-22.tex
asterLA.9-11.tex
```

A real example, file names of versions of a paper I wrote with a co-author
without version
control.  This works but is highly sub-optimal.  Only one author can work
at a time because there is no good way to merge simultaneous changes.
Nor is there any obvious ownership of the versions.  It is hard to tell
who did what when.

### A Plethora of Version Control Systems

Ripped off from Wikipedia ([under "Version control"](https://en.wikipedia.org/wiki/Version_control)).

 Local Only     Client-Server       Distributed
------------   -----------------   ----------------
SCCS (1972)    CVS (1986)          BitKeeper (1998)
RCS (1982)     ClearCase (1992)    GNU arch (2001)
               Perforce (1995)     Darcs (2002)
               Subversion (2000)   Monotone (2003)
                                   Bazaar (2005)
                                   Git (2005)
                                   Mercurial (2005)

There were more, but I've only kept the ones I'd heard of.

Don't worry.  We're only going to talk about one (git).


### Mindshare

Starting from nowhere in 2005, `git` has gotten dominant mindshare, at least
among free and open source systems.

In [Google Trends](http://www.google.com/trends/explore#q=%2Fm%2F05vqwg%2C%20%2Fm%2F012ct9%2C%20%2Fm%2F09d6g%2C%20%2Fm%2F08441_%2C%20%2Fm%2F04g0kcw&cmpt=q&tz=), the only searches that are trending up are for `git` and github.
Searches for competing version control systems are trending down.

Many well known open-source projects are on git.  The Linux kernel (of course
since Linus Torvalds wrote git to be the VCS for the kernel), android (as in
phones), Ruby on Rails, Gnome, Qt, KDE, X, Perl, and GNU Emacs.

Some aren't.  R is still on Subversion.  Firefox, Go, Python, Vim are
on Mercurial.

### Why?

Section 28.1.1.1 of the GNU Emacs manual.

Version control systems provide you with three important capabilities:

 * **Reversibility:** the ability to back up to a previous state if you discover that some modification you did was a mistake or a bad idea.

 * **Concurrency:** the ability to have many people modifying the same collection of files knowing that conflicting modifications can be detected and resolved.

 * **History:** the ability to attach historical data to your data, such as explanatory comments about the intention behind each change to it. Even for a programmer working solo, change histories are an important aid to memory; for a multi-person project, they are a vitally important form of communication among developers. 

## Git

### Getting Git

Type ``git'' into Google and follow the first link it gives you
http://git-scm.com/.

Under "downloads" it tells you how to get `git` for Windows and for Mac OS X.

If you have Linux, it just comes with (use the installer for your distribution).

E. g., on Ubuntu
```
sudo apt-get update
sudo apt-get install git
```

### What?

From Wikipedia under [Git](https://en.wikipedia.org/wiki/Git):

 * Torvalds has quipped about the name *git,* which is British English slang meaning "unpleasant person." Torvalds said: "I'm an egotistical bastard, and I name all my projects after myself. First 'Linux', now 'git'."

 * The man page describes Git as "the stupid content tracker".

From memory:

 * Linus has also said that it was a short name that hadn't already been used for a UNIX command.

### Using Git

#### From the Command Line

#### RStudio

