<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to Data Analysis with R &amp; Reproducible Data Science</title>
  <meta name="description" content="Introduction to Data Analysis with R &amp; Reproducible Data Science">
  <meta name="generator" content="bookdown 0.4 and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to Data Analysis with R &amp; Reproducible Data Science" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="IRSAAtUMn/RWorkshop17/docs" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to Data Analysis with R &amp; Reproducible Data Science" />
  
  
  

<meta name="author" content="Institute for Research in Statistics and its Applications at the University of Minnesota">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="data-visualization.html">
<link rel="next" href="linear-regression-in-r.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Home</a></li>
<li class="chapter" data-level="1" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html"><i class="fa fa-check"></i><b>1</b> Introduction to R &amp; RStudio</a></li>
<li class="chapter" data-level="2" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>2</b> Data Visualization</a></li>
<li class="chapter" data-level="3" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html"><i class="fa fa-check"></i><b>3</b> Simple Statistics in R</a><ul>
<li class="chapter" data-level="3.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#chapter-outline-and-goals"><i class="fa fa-check"></i><b>3.1</b> Chapter Outline and Goals</a></li>
<li class="chapter" data-level="3.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#minnesota-beer-data"><i class="fa fa-check"></i><b>3.2</b> Minnesota Beer Data</a><ul>
<li class="chapter" data-level="3.2.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#overview"><i class="fa fa-check"></i><b>3.2.1</b> Overview</a></li>
<li class="chapter" data-level="3.2.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#load-the-data"><i class="fa fa-check"></i><b>3.2.2</b> Load the Data</a></li>
<li class="chapter" data-level="3.2.3" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#look-at-the-data"><i class="fa fa-check"></i><b>3.2.3</b> Look at the Data</a></li>
<li class="chapter" data-level="3.2.4" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#plot-the-data"><i class="fa fa-check"></i><b>3.2.4</b> Plot the Data</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#descriptive-statistics-in-r"><i class="fa fa-check"></i><b>3.3</b> Descriptive Statistics in R</a><ul>
<li class="chapter" data-level="3.3.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#overview-1"><i class="fa fa-check"></i><b>3.3.1</b> Overview</a></li>
<li class="chapter" data-level="3.3.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#minimum-and-maximum"><i class="fa fa-check"></i><b>3.3.2</b> Minimum and Maximum</a></li>
<li class="chapter" data-level="3.3.3" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#mean-standard-deviation-and-variance"><i class="fa fa-check"></i><b>3.3.3</b> Mean, Standard Deviation, and Variance</a></li>
<li class="chapter" data-level="3.3.4" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#medians-and-quantiles"><i class="fa fa-check"></i><b>3.3.4</b> Medians and Quantiles</a></li>
<li class="chapter" data-level="3.3.5" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#factor-level-information"><i class="fa fa-check"></i><b>3.3.5</b> Factor Level Information</a></li>
<li class="chapter" data-level="3.3.6" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#covariances-and-correlations"><i class="fa fa-check"></i><b>3.3.6</b> Covariances and Correlations</a></li>
<li class="chapter" data-level="3.3.7" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#applying-functions-to-multiple-variables"><i class="fa fa-check"></i><b>3.3.7</b> Applying Functions to Multiple Variables</a></li>
<li class="chapter" data-level="3.3.8" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#applying-functions-at-levels-of-factors"><i class="fa fa-check"></i><b>3.3.8</b> Applying Functions at Levels of Factors</a></li>
<li class="chapter" data-level="3.3.9" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#making-a-table"><i class="fa fa-check"></i><b>3.3.9</b> Making a Table</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#students-t-test-in-r"><i class="fa fa-check"></i><b>3.4</b> Student’s t-Test in R</a><ul>
<li class="chapter" data-level="3.4.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#one-sample-t-test"><i class="fa fa-check"></i><b>3.4.1</b> One Sample t-Test</a></li>
<li class="chapter" data-level="3.4.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#two-sample-t-test"><i class="fa fa-check"></i><b>3.4.2</b> Two Sample t-Test</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#one-way-anova-in-r"><i class="fa fa-check"></i><b>3.5</b> One-Way ANOVA in R</a><ul>
<li class="chapter" data-level="3.5.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#omnibus-f-test"><i class="fa fa-check"></i><b>3.5.1</b> Omnibus F-Test</a></li>
<li class="chapter" data-level="3.5.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#pairwise-comparisons-tukeys-hsd"><i class="fa fa-check"></i><b>3.5.2</b> Pairwise Comparisons (Tukey’s HSD)</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#correlation-tests-in-r"><i class="fa fa-check"></i><b>3.6</b> Correlation Tests in R</a></li>
<li class="chapter" data-level="3.7" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#exercises"><i class="fa fa-check"></i><b>3.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html"><i class="fa fa-check"></i><b>4</b> Linear Regression in R</a></li>
<li class="chapter" data-level="5" data-path="quantile-regression-in-r.html"><a href="quantile-regression-in-r.html"><i class="fa fa-check"></i><b>5</b> Quantile Regression in R</a></li>
<li class="chapter" data-level="6" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html"><i class="fa fa-check"></i><b>6</b> An R Markdown Demo</a></li>
<li class="chapter" data-level="7" data-path="git-version-control.html"><a href="git-version-control.html"><i class="fa fa-check"></i><b>7</b> Git (Version Control)</a></li>
<li class="chapter" data-level="8" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html"><i class="fa fa-check"></i><b>8</b> Using R Reproducibly</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Data Analysis with R &amp; Reproducible Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simple-statistics-in-r" class="section level1">
<h1><span class="header-section-number"> 3</span> Simple Statistics in R</h1>
<p><em>Author: Nathaniel E. Helwig</em></p>
<div id="chapter-outline-and-goals" class="section level2">
<h2><span class="header-section-number">3.1</span> Chapter Outline and Goals</h2>
<p>In this chapter, we will cover how to…</p>
<ul>
<li>Load, explore, and summarize data</li>
<li>Calculate descriptive statistics</li>
<li>Create reproducible plots and tables</li>
<li>Perform one and two sample <em>t</em>-tests</li>
<li>Fit one-way analysis of variance models</li>
<li>Conduct simple correlation tests</li>
</ul>
<p>R has many helpful functions for simple descriptive and inferential statistics, which make reproducible research easy!</p>
</div>
<div id="minnesota-beer-data" class="section level2">
<h2><span class="header-section-number">3.2</span> Minnesota Beer Data</h2>
<div id="overview" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Overview</h3>
<p>The Minnesota beer data has 44 beers measured on 7 variables:</p>
<ol style="list-style-type: decimal">
<li><em>Brewery</em>: Name of the brewery (<strong>factor</strong> with 8 levels)</li>
<li><em>Beer</em>: Name of the beer (<strong>factor</strong> with 44 levels)</li>
<li><em>Description</em>: Description of the beer (<strong>factor</strong> with 37 levels)</li>
<li><em>Style</em>: Style of the beer (<strong>factor</strong> with 3 levels)</li>
<li><em>ABV</em>: Alcohol by volume (<strong>numeric</strong>)</li>
<li><em>IBU</em>: International bitterness units (<strong>integer</strong>)</li>
<li><em>Rating</em>: Beer Advocate rating (<strong>integer</strong>)</li>
</ol>
<p>Data obtained by NEH from <a href="http://beeradvocate.com">Beer Advocate</a> and the websites of the eight breweries.</p>
</div>
<div id="load-the-data" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Load the Data</h3>
<p>Use the <strong>read.csv</strong> function to load the <em>beer</em> data into R</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">beer &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;http://users.stat.umn.edu/~helwig/notes/MNbeer.csv&quot;</span>)</code></pre></div>
<p>The <strong>dim</strong> function returns the number of rows and columns of the data frame</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(beer)</code></pre></div>
<pre><code>## [1] 44  7</code></pre>
<p>The <em>beer</em> data frame has 44 beers (rows) measured on 7 variables (columns).</p>
<p>The <strong>names</strong> function returns the names of the variables in a data frame</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(beer)</code></pre></div>
<pre><code>## [1] &quot;Brewery&quot;     &quot;Beer&quot;        &quot;Description&quot; &quot;Style&quot;       &quot;ABV&quot;        
## [6] &quot;IBU&quot;         &quot;Rating&quot;</code></pre>
</div>
<div id="look-at-the-data" class="section level3">
<h3><span class="header-section-number">3.2.3</span> Look at the Data</h3>
<p>The <strong>head</strong> function returns the first six lines of a data frame</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(beer)</code></pre></div>
<pre><code>##       Brewery         Beer              Description Style ABV IBU Rating
## 1     Bauhaus  Wonderstuff     New Bohemian Pilsner Lager 5.4  48     88
## 2     Bauhaus    Stargazer German Style Schwarzbier Lager 5.0  28     87
## 3     Bauhaus  Wagon Party    West Cost Style Lager Lager 5.4  55     86
## 4     Bauhaus    Sky-Five!        Midwest Coast IPA   IPA 6.7  70     86
## 5 Bent Paddle         Kanu         Session Pale Ale   Ale 4.8  48     85
## 6 Bent Paddle Venture Pils            Pilsner Lager Lager 5.0  38     87</code></pre>
<p>The <strong>summary</strong> function provides a summary of each variable in a data frame</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(beer)</code></pre></div>
<pre><code>##           Brewery                Beer                    Description
##  Indeed       :7   14* ESB         : 1   India Pale Ale        : 5  
##  Summit       :7   B-Side Pils     : 1   English IPA           : 2  
##  Surly        :7   Batch 300       : 1   Pilsner Lager         : 2  
##  Bent Paddle  :5   Bender          : 1   Porter                : 2  
##  Fulton       :5   Bent Hop        : 1   American Blonde Ale   : 1  
##  Urban Growler:5   Big Boot Rye IPA: 1   Belgian Style Pale Ale: 1  
##  (Other)      :8   (Other)         :38   (Other)               :31  
##    Style         ABV             IBU            Rating     
##  Ale  :18   Min.   :4.200   Min.   :15.00   Min.   :79.00  
##  IPA  :17   1st Qu.:5.200   1st Qu.:33.00   1st Qu.:85.00  
##  Lager: 9   Median :5.600   Median :48.50   Median :87.00  
##             Mean   :5.818   Mean   :51.07   Mean   :87.18  
##             3rd Qu.:6.500   3rd Qu.:68.25   3rd Qu.:90.00  
##             Max.   :7.500   Max.   :99.00   Max.   :98.00  
## </code></pre>
</div>
<div id="plot-the-data" class="section level3">
<h3><span class="header-section-number">3.2.4</span> Plot the Data</h3>
<p>The <strong>brewer.pal</strong> function in the <em>RColorBrewer</em> package creates <a href="http://ColorBrewer.org">ColorBrewer palettes</a> for plotting</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(RColorBrewer)
MyColors &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="kw">nlevels</span>(beer$Style), <span class="st">&quot;Pastel1&quot;</span>)</code></pre></div>
<p>The <strong>boxplot</strong> function creates simple boxplots</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(ABV ~<span class="st"> </span>Style, <span class="dt">data =</span> beer, <span class="dt">ylab =</span> <span class="st">&quot;Alcohol By Volume (ABV)&quot;</span>,
        <span class="dt">main =</span> <span class="st">&quot;Alcohol by Style of Beer&quot;</span>, <span class="dt">col =</span> MyColors)</code></pre></div>
<p><img src="RWorkshop17_files/figure-html/unnamed-chunk-7-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>The <strong>plot</strong> function creates generic X-Y scatterplots</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">StyleInt &lt;-<span class="st"> </span><span class="kw">as.integer</span>(beer$Style)
<span class="kw">plot</span>(beer$IBU, beer$ABV, <span class="dt">xlab =</span> <span class="st">&quot;International Bitterness Units (IBU)&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Alcohol By Volume (ABV)&quot;</span>, <span class="dt">pch =</span> StyleInt +<span class="st"> </span><span class="dv">14</span>,
     <span class="dt">main =</span> <span class="st">&quot;Bitterness vs Alcohol&quot;</span>, <span class="dt">col =</span> MyColors[StyleInt])
<span class="kw">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="dt">legend =</span> <span class="kw">levels</span>(beer$Style), <span class="dt">pch =</span> <span class="dv">15</span>:<span class="dv">17</span>,
       <span class="dt">col =</span> MyColors, <span class="dt">bty =</span> <span class="st">&quot;n&quot;</span>)</code></pre></div>
<p><img src="RWorkshop17_files/figure-html/beercolors-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>R has functions for saving plots to various figure formats:</p>
<ul>
<li><strong>bmp</strong> function for bitmap graphics</li>
<li><strong>jpeg</strong> function for JPEG graphics</li>
<li><strong>png</strong> function for Portable Network Graphics</li>
<li><strong>tiff</strong> function for Tag Image File Format graphics</li>
<li><strong>pdf</strong> or <strong>dev.copy2pdf</strong> functions for Portable Document Format graphics</li>
<li><strong>postscript</strong> or <strong>dev.copy2eps</strong> functions for PostScript graphics</li>
</ul>
</div>
</div>
<div id="descriptive-statistics-in-r" class="section level2">
<h2><span class="header-section-number">3.3</span> Descriptive Statistics in R</h2>
<div id="overview-1" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Overview</h3>
<p>We often need to calculate simple descriptive statistics of variables in a data frame, e.g., to make summary tables. As we have already seen, R is a function based and object oriented programming language. To obtain descriptive statistics, we input an object (e.g., column of a data frame) into the corresponding function. Thankfully, functions in R often have intuitive names—you can typically guess the name of the function you need!</p>
</div>
<div id="minimum-and-maximum" class="section level3">
<h3><span class="header-section-number">3.3.2</span> Minimum and Maximum</h3>
<p>To calculate the minimum or maximum of a variable, we could use the <strong>min</strong> or <strong>max</strong> functions</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">min</span>(beer$ABV)</code></pre></div>
<pre><code>## [1] 4.2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">max</span>(beer$ABV)</code></pre></div>
<pre><code>## [1] 7.5</code></pre>
<p>or the <strong>range</strong> function to return both the minimum and maximum</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">range</span>(beer$ABV)</code></pre></div>
<pre><code>## [1] 4.2 7.5</code></pre>
<p>The minimum ABV in the sample is 4.2% and the maximum is 7.5%. To determine which beers have the min/max ABV values, we can use the <strong>which.min</strong> and <strong>which.max</strong> functions</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">minmaxID &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">which.min</span>(beer$ABV), <span class="kw">which.max</span>(beer$ABV))
beer[minmaxID,]</code></pre></div>
<pre><code>##    Brewery              Beer      Description Style ABV IBU Rating
## 12  Indeed Lucy Session Sour Session Sour Ale   Ale 4.2  27     86
## 38   Surly         Overrated   West Coast IPA   IPA 7.5  69     91</code></pre>
</div>
<div id="mean-standard-deviation-and-variance" class="section level3">
<h3><span class="header-section-number">3.3.3</span> Mean, Standard Deviation, and Variance</h3>
<p>The <strong>mean</strong> function calculates the sample mean <span class="math inline">\(\bar{x} = \frac{1}{n}\sum_{i=1}^n x_i\)</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(beer$ABV)</code></pre></div>
<pre><code>## [1] 5.818182</code></pre>
<p>The <strong>sd</strong> function calculates the sample standard deviation <span class="math inline">\(s = \{\frac{1}{n-1} \sum_{i=1}^n (x_i - \bar{x})^2\}^{1/2}\)</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(beer$ABV)</code></pre></div>
<pre><code>## [1] 0.8176178</code></pre>
<p>The <strong>var</strong> function calculates the sample variance <span class="math inline">\(s^2 = \frac{1}{n-1} \sum_{i=1}^n (x_i - \bar{x})^2\)</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">var</span>(beer$ABV)</code></pre></div>
<pre><code>## [1] 0.6684989</code></pre>
<p>The mean ABV is about 5.82% with a standard deviation of about 0.82% (variance of about 0.67%).</p>
</div>
<div id="medians-and-quantiles" class="section level3">
<h3><span class="header-section-number">3.3.4</span> Medians and Quantiles</h3>
<p>The <strong>median</strong> function calculates the sample median of a vector</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">median</span>(beer$ABV)</code></pre></div>
<pre><code>## [1] 5.6</code></pre>
<p>and the <strong>quantile</strong> function can be used for other quantiles</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">quantile</span>(beer$ABV)</code></pre></div>
<pre><code>##   0%  25%  50%  75% 100% 
##  4.2  5.2  5.6  6.5  7.5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">quantile</span>(beer$ABV, <span class="dt">probs =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dt">length=</span><span class="dv">11</span>))</code></pre></div>
<pre><code>##   0%  10%  20%  30%  40%  50%  60%  70%  80%  90% 100% 
## 4.20 4.86 5.16 5.30 5.42 5.60 6.20 6.40 6.50 6.87 7.50</code></pre>
<p>The median is 5.6% ABV, which implies that half of the beers have at least 5.6% ABV.</p>
</div>
<div id="factor-level-information" class="section level3">
<h3><span class="header-section-number">3.3.5</span> Factor Level Information</h3>
<p>The <strong>levels</strong> function extracts the levels (i.e., unique values) of a factor variable</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">levels</span>(beer$Style)</code></pre></div>
<pre><code>## [1] &quot;Ale&quot;   &quot;IPA&quot;   &quot;Lager&quot;</code></pre>
<p>and the <strong>nlevels</strong> function returns the number of levels of a factor</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">nlevels</span>(beer$Style)</code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>The 44 beers are classified into one of three Styles: Ale, IPA, or Lager.</p>
</div>
<div id="covariances-and-correlations" class="section level3">
<h3><span class="header-section-number">3.3.6</span> Covariances and Correlations</h3>
<p>The <strong>cov</strong> function calculates the covariance <span class="math inline">\(c = \frac{1}{n-1} \sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})\)</span> between two variables</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cov</span>(beer$ABV, beer$IBU)</code></pre></div>
<pre><code>## [1] 13.22664</code></pre>
<p>or a covariance matrix between the columns of an input data frame</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cov</span>(beer[, <span class="kw">c</span>(<span class="st">&quot;ABV&quot;</span>,<span class="st">&quot;IBU&quot;</span>,<span class="st">&quot;Rating&quot;</span>)])</code></pre></div>
<pre><code>##               ABV       IBU    Rating
## ABV     0.6684989  13.22664  1.510571
## IBU    13.2266385 461.18129 30.871036
## Rating  1.5105708  30.87104 13.919662</code></pre>
<p>The <strong>cor</strong> function calculates the correlation <span class="math inline">\(r = \frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}{\{\sum_{i=1}^n (x_i - \bar{x})^2 \}^{1/2} \{\sum_{i=1}^n (y_i - \bar{y})^2 \}^{1/2} }\)</span> between two variables</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(beer$ABV, beer$IBU)</code></pre></div>
<pre><code>## [1] 0.7532919</code></pre>
<p>or a correlation matrix between the columns of an input data frame</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(beer[, <span class="kw">c</span>(<span class="st">&quot;ABV&quot;</span>,<span class="st">&quot;IBU&quot;</span>,<span class="st">&quot;Rating&quot;</span>)])</code></pre></div>
<pre><code>##              ABV       IBU    Rating
## ABV    1.0000000 0.7532919 0.4951952
## IBU    0.7532919 1.0000000 0.3853018
## Rating 0.4951952 0.3853018 1.0000000</code></pre>
</div>
<div id="applying-functions-to-multiple-variables" class="section level3">
<h3><span class="header-section-number">3.3.7</span> Applying Functions to Multiple Variables</h3>
<p>To apply a function to several columns, we can use the <strong>apply</strong> function</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">apply</span>(beer[, <span class="kw">c</span>(<span class="st">&quot;ABV&quot;</span>,<span class="st">&quot;IBU&quot;</span>,<span class="st">&quot;Rating&quot;</span>)], <span class="dv">2</span>, range)</code></pre></div>
<pre><code>##      ABV IBU Rating
## [1,] 4.2  15     79
## [2,] 7.5  99     98</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">apply</span>(beer[, <span class="kw">c</span>(<span class="st">&quot;ABV&quot;</span>,<span class="st">&quot;IBU&quot;</span>,<span class="st">&quot;Rating&quot;</span>)], <span class="dv">2</span>, mean)</code></pre></div>
<pre><code>##       ABV       IBU    Rating 
##  5.818182 51.068182 87.181818</code></pre>
</div>
<div id="applying-functions-at-levels-of-factors" class="section level3">
<h3><span class="header-section-number">3.3.8</span> Applying Functions at Levels of Factors</h3>
<p>Use the <strong>tapply</strong> (ragged apply) function to apply some function to a numeric variable separately at each level of a factor variable. For example, we could apply the <strong>range</strong> function to the <em>ABV</em> variable separately for each <em>Style</em> of beer</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tapply</span>(beer$ABV, beer$Style, range)</code></pre></div>
<pre><code>## $Ale
## [1] 4.2 7.0
## 
## $IPA
## [1] 5.8 7.5
## 
## $Lager
## [1] 4.5 5.4</code></pre>
<p>In the given sample, Ales range from 4.2% to 7% ABV, India Pale Ales range from 5.8% to 7.5% ABV, and Lagers range from 4.5% to 5.4% ABV.</p>
</div>
<div id="making-a-table" class="section level3">
<h3><span class="header-section-number">3.3.9</span> Making a Table</h3>
<p>Use the <strong>cbind</strong> (column combine) function in combination with the <strong>tapply</strong> function to create tables</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tab1 &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">tapply</span>(beer$Rating, beer$Style, length),
              <span class="kw">tapply</span>(beer$ABV, beer$Style, mean),
              <span class="kw">tapply</span>(beer$ABV, beer$Style, sd),
              <span class="kw">tapply</span>(beer$IBU, beer$Style, mean),
              <span class="kw">tapply</span>(beer$IBU, beer$Style, sd),
              <span class="kw">tapply</span>(beer$Rating, beer$Style, mean),
              <span class="kw">tapply</span>(beer$Rating, beer$Style, sd))
<span class="kw">colnames</span>(tab1) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;n&quot;</span>, <span class="st">&quot;ABV.Mean&quot;</span>, <span class="st">&quot;ABV.SD&quot;</span>, <span class="st">&quot;IBU.Mean&quot;</span>, 
                    <span class="st">&quot;IBU.SD&quot;</span>, <span class="st">&quot;Rating.Mean&quot;</span>, <span class="st">&quot;Rating.SD&quot;</span>)
rtab1 &lt;-<span class="st"> </span><span class="kw">round</span>(tab1, <span class="dv">2</span>)
rtab1</code></pre></div>
<pre><code>##        n ABV.Mean ABV.SD IBU.Mean IBU.SD Rating.Mean Rating.SD
## Ale   18     5.49   0.67    39.00  12.28       86.83      3.50
## IPA   17     6.56   0.46    73.53  10.59       88.18      4.54
## Lager  9     5.06   0.35    32.78  12.58       86.00      1.87</code></pre>
<p>The <strong>write.csv</strong> function can be used to save the table</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">write.csv</span>(rtab1, <span class="dt">file =</span> <span class="st">&quot;~/Desktop/table1.csv&quot;</span>, <span class="dt">row.names =</span> <span class="ot">TRUE</span>)</code></pre></div>
<p>After some minor stylistic edits, the table is ready for publication—without having to manually type or copy-paste numbers!</p>
<p>The <strong>kable</strong> function (in the <em>knitr</em> package) includes nicely formatted tables in R Markdown documents</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(knitr)
<span class="kw">kable</span>(rtab1, <span class="dt">caption =</span> <span class="st">&quot;Table 1: Sample size (n) and variable means and standard deviations (SD) for each style of beer.&quot;</span>)</code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-26">Table 3.1: </span>Table 1: Sample size (n) and variable means and standard deviations (SD) for each style of beer.</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">n</th>
<th align="right">ABV.Mean</th>
<th align="right">ABV.SD</th>
<th align="right">IBU.Mean</th>
<th align="right">IBU.SD</th>
<th align="right">Rating.Mean</th>
<th align="right">Rating.SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ale</td>
<td align="right">18</td>
<td align="right">5.49</td>
<td align="right">0.67</td>
<td align="right">39.00</td>
<td align="right">12.28</td>
<td align="right">86.83</td>
<td align="right">3.50</td>
</tr>
<tr class="even">
<td>IPA</td>
<td align="right">17</td>
<td align="right">6.56</td>
<td align="right">0.46</td>
<td align="right">73.53</td>
<td align="right">10.59</td>
<td align="right">88.18</td>
<td align="right">4.54</td>
</tr>
<tr class="odd">
<td>Lager</td>
<td align="right">9</td>
<td align="right">5.06</td>
<td align="right">0.35</td>
<td align="right">32.78</td>
<td align="right">12.58</td>
<td align="right">86.00</td>
<td align="right">1.87</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="students-t-test-in-r" class="section level2">
<h2><span class="header-section-number">3.4</span> Student’s t-Test in R</h2>
<div id="one-sample-t-test" class="section level3">
<h3><span class="header-section-number">3.4.1</span> One Sample t-Test</h3>
<p>Mass produced beers (e.g., Bud Light, Miller Lite, etc.) have 4.2% ABV. Suppose we want to test if Minnesota beers have the same mean ABV as mass produced beers <span class="math display">\[
H_0: \mu = 4.2 \quad \mbox{vs.} \quad H_1: \mu \neq 4.2
\]</span> where <span class="math inline">\(\mu\)</span> is the mean ABV, and <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span> denote the null and alternative hypotheses. Assuming that the ABV scores are normally distributed, the <strong>t.test</strong> function can be used to test the null hypothesis</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(beer$ABV, <span class="dt">mu =</span> <span class="fl">4.2</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  beer$ABV
## t = 13.128, df = 43, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 4.2
## 95 percent confidence interval:
##  5.569603 6.066760
## sample estimates:
## mean of x 
##  5.818182</code></pre>
<p>The observed <em>t</em> statistic is <span class="math inline">\(t = 13.13\)</span> with 43 degrees of freedom, resulting in a p-value of essentially zero—we reject <span class="math inline">\(H_0\)</span> using any standard <span class="math inline">\(\alpha\)</span> level. The sample mean is <span class="math inline">\(\bar{x} = 5.8\)</span>% ABV and the 95% confidence interval for the <span class="math inline">\(\mu\)</span> (population mean ABV of Minnesota beers) is 5.6% to 6.1% ABV.</p>
<p>If we expect that the Minnesota beers have higher ABV than mass produced beers, i.e., <span class="math display">\[
H_0: \mu = 4.2 \quad \mbox{vs.} \quad H_1: \mu &gt; 4.2
\]</span> we need to adjust the <em>alternative</em> input</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(beer$ABV, <span class="dt">mu =</span> <span class="fl">4.2</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  beer$ABV
## t = 13.128, df = 43, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is greater than 4.2
## 95 percent confidence interval:
##  5.610972      Inf
## sample estimates:
## mean of x 
##  5.818182</code></pre>
<p>The only noteworthy difference is that the confidence interval is now a 95% lower bound for the mean ABV of Minnesota beers, which we expect to be at least 5.6% ABV. Note that changing the alternative also changes the p-value, but for this example we do not notice (because the p-value is so small).</p>
</div>
<div id="two-sample-t-test" class="section level3">
<h3><span class="header-section-number">3.4.2</span> Two Sample t-Test</h3>
<p>Suppose that we want to test if IPA beers have higher ABV than non-IPAs (Ales and Lagers) <span class="math display">\[
H_0: \mu_1 = \mu_2 \quad \mbox{vs.} \quad H_1: \mu_1 &gt; \mu_2
\]</span> where <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span> denote the mean ABV of IPA and non-IPA beers, respectively.</p>
<p>To use the <strong>t.test</strong> function for a two sample <em>t</em>-test, we need to input two vectors</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">beer$IPA &lt;-<span class="st"> </span>(beer$Style ==<span class="st"> &quot;IPA&quot;</span>)
<span class="kw">t.test</span>(beer$ABV[beer$IPA], beer$ABV[!beer$IPA], <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  beer$ABV[beer$IPA] and beer$ABV[!beer$IPA]
## t = 7.4454, df = 40.527, p-value = 2.093e-09
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  0.9415048       Inf
## sample estimates:
## mean of x mean of y 
##  6.564706  5.348148</code></pre>
<p>The observed <em>t</em> statistic is <span class="math inline">\(t = 7.45\)</span> with 40.53 degrees of freedom, resulting in a p-value of essentially zero—we reject <span class="math inline">\(H_0\)</span> using any standard <span class="math inline">\(\alpha\)</span> level. The sample mean difference is <span class="math inline">\(\bar{x}_1 - \bar{x}_2 = 1.22\)</span>% ABV and the 95% lower-bound confidence interval reveals that we expect IPAs to have at least 0.94% more ABV than non-IPAs.</p>
<p>The default uses the Welch version, which does not assume equal variance for the two groups. The <em>var.equal</em> input can be used to change this assumption, which produces the classic two sample <em>t</em>-test</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(beer$ABV[beer$IPA], beer$ABV[!beer$IPA], <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>,
       <span class="dt">var.equal =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  beer$ABV[beer$IPA] and beer$ABV[!beer$IPA]
## t = 6.9809, df = 42, p-value = 7.74e-09
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  0.9234437       Inf
## sample estimates:
## mean of x mean of y 
##  6.564706  5.348148</code></pre>
<p>Note that the observed <em>t</em>-test statistic, p-value, and 95% lower-bound are slightly different, but our conclusion does not change: we expect IPAs to have at least 0.9% more ABV than non-IPAs.</p>
</div>
</div>
<div id="one-way-anova-in-r" class="section level2">
<h2><span class="header-section-number">3.5</span> One-Way ANOVA in R</h2>
<div id="omnibus-f-test" class="section level3">
<h3><span class="header-section-number">3.5.1</span> Omnibus F-Test</h3>
<p>Extending the previous example, suppose that we want to test if the mean ABV differs for the three Styles of beer <span class="math display">\[
H_0: \mu_j = \mu  \mbox{ for all } j \quad \mbox{vs.} \quad H_1: \mu_j \neq \mu \mbox{ for some } j
\]</span> where <span class="math inline">\(\mu_j\)</span> denotes the mean ABV of the three Styles of beer: Ales, IPAs, and Lagers. Assuming that the ABV scores a normally distributed, we can use the <strong>aov</strong> (analysis of variance) function</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">amod &lt;-<span class="st"> </span><span class="kw">aov</span>(ABV ~<span class="st"> </span>Style, <span class="dt">data =</span> beer)
<span class="kw">summary</span>(amod)</code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Style        2  16.59   8.297      28 2.16e-08 ***
## Residuals   41  12.15   0.296                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The observed <em>F</em> statistic is <span class="math inline">\(F = 28\)</span> with 2 numerator and 41 denominator degrees of freedom, resulting in a p-value of essentially zero—we reject <span class="math inline">\(H_0\)</span> using any standard <span class="math inline">\(\alpha\)</span> level. We conclude that the mean ABV of Minnesota beers depends on the Style of beer, but the results do not directly reveal which Styles significantly differ from one another.</p>
</div>
<div id="pairwise-comparisons-tukeys-hsd" class="section level3">
<h3><span class="header-section-number">3.5.2</span> Pairwise Comparisons (Tukey’s HSD)</h3>
<p>To determine which Styles significantly differ in their mean ABV, we can use Tukey’s Honest Significant Differences (HSD) procedure via the <strong>TukeyHSD</strong> function</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">TukeyHSD</span>(amod)</code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = ABV ~ Style, data = beer)
## 
## $Style
##                 diff        lwr        upr     p adj
## IPA-Ale    1.0702614  0.6225693  1.5179536 0.0000024
## Lager-Ale -0.4388889 -0.9793078  0.1015301 0.1313124
## Lager-IPA -1.5091503 -2.0548418 -0.9634589 0.0000001</code></pre>
<p>The pairwise comparisons reveal that</p>
<ul>
<li>IPAs have significantly higher mean ABV than Ales. The estimated mean difference is <span class="math inline">\(\hat{\delta}_1 = \hat{\mu}_{2} - \hat{\mu}_1 = 1.07\)</span> with 95% confidence interval <span class="math inline">\(\delta_1 \in [0.62, 1.52]\)</span>.</li>
<li>Lagers and Ales do not significantly differ in mean ABV. The estimated mean difference is <span class="math inline">\(\hat{\delta}_2 = \hat{\mu}_{3} - \hat{\mu}_1 = -0.44\)</span> with 95% confidence interval <span class="math inline">\(\delta_2 \in [-0.98, 0.10]\)</span>.</li>
<li>Lagers have significantly lower mean ABV than IPAs. The estimated mean difference is <span class="math inline">\(\hat{\delta}_3 = \hat{\mu}_{3} - \hat{\mu}_2 = -1.51\)</span> with 95% confidence interval <span class="math inline">\(\delta_3 \in [-2.05, -0.96]\)</span>.</li>
</ul>
</div>
</div>
<div id="correlation-tests-in-r" class="section level2">
<h2><span class="header-section-number">3.6</span> Correlation Tests in R</h2>
<p>Suppose that we want to test if a beer’s ABV and Rating are postively correlated <span class="math display">\[
H_0: \rho = 0 \quad \mbox{vs.} \quad H_1: \rho &gt; 0
\]</span> where <span class="math inline">\(\rho\)</span> is the population correlation between the ABV and Rating. Assuming that the ABV and Rating variables follow a bivariate normal distribution, we can use the <strong>cor.test</strong> function</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(beer$ABV, beer$Rating, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>)</code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  beer$ABV and beer$Rating
## t = 3.6939, df = 42, p-value = 0.000316
## alternative hypothesis: true correlation is greater than 0
## 95 percent confidence interval:
##  0.2784833 1.0000000
## sample estimates:
##       cor 
## 0.4951952</code></pre>
<p>The estimated sample correlation is <span class="math inline">\(r = 0.495\)</span> and the 95% lower-bound confidence interval reveals that we expect the ABV and Ratings to have a positive correlation of at least <span class="math inline">\(\rho = 0.28\)</span>.</p>
</div>
<div id="exercises" class="section level2">
<h2><span class="header-section-number">3.7</span> Exercises</h2>
<ol style="list-style-type: decimal">
<li>Load the Minnesota Beer Data into R.</li>
<li>Make a boxplot of the IBUs by Style of beer.</li>
<li>Make a scatterplot of the ABV (x-axis) by Rating (y-axis).</li>
<li>Calculate some descriptive statistics for the IBU variable.</li>
<li>Create a table showing the sample size and variable means and standard deviations for each Brewery.</li>
<li>Repeat the <em>t</em>-tests using the IBU variable as the response.</li>
<li>Repeat the one-way ANOVA using the IBU variable as the response.</li>
<li>Repeat the correlation test using the IBU and Rating variables.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-visualization.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="linear-regression-in-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"download": null,
"toc": {
"collapse": "section",
"depth": 2,
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
